blank_issues_enabled: false
contact_links:
  - name: GitHub Discussions
    url: https://github.com/paradedb/paradedb/discussions
    about: Please ask and answer general questions here.
  - name: ParadeDB Community Slack
    url: https://www.paradedb.com/slack
    about: Our Slack community is the best place to get quick help and feedback.
